from fastapi import APIRouter
import resend
from app.config import settings
import json

resend.api_key = settings.RESEND_API_KEY
router = APIRouter()

async def send_report(data: dict):
    subject = "Kiyara Activity Report"
    html = f"""
    <h2>🤖 Kiyara Report</h2>
    <pre>{json.dumps(data, indent=2, ensure_ascii=False)}</pre>
    <p><i>Auto-generated by Kiyara AI Agent</i></p>
    """
    try:
        resp = resend.Emails.send({
            "from": "Kiyara <reports@kiyara.ai>",
            "to": [settings.ADMIN_EMAIL],
            "subject": subject,
            "html": html
        })
        print(f"📧 Email sent: {resp}")
        return resp
    except Exception as e:
        print(f"Email failed: {e}")
        return None

@router.post("/test")
async def test_email():
    await send_report({"test": "Hello from Kiyara"})
    return {"status": "sent"}